/*
 Generated by typeshare 1.13.4
*/

export interface GitHubData {
	lastCommitAt: string;
	lastCommitMsg: string;
	openIssues: number;
	openPrs: number;
	ciStatus?: string;
	fetchedAt: string;
}

export interface GoalEntry {
	date: string;
	text: string;
	done?: boolean;
}

export interface Habit {
	id?: string;
	name: string;
	streak: number;
	icon: string;
	lastChecked?: string;
	targetStreak?: number;
	bestStreak?: number;
	checkHistory?: string[];
	notes?: string;
}

export interface IntentionEntry {
	date: string;
	text: string;
	done?: boolean;
}

export interface MomentumEntry {
	date: string;
	score: number;
	tier: string;
}

export interface PomodoroDay {
	date: string;
	count: number;
}

export interface PomodoroDurations {
	focus: number;
	break: number;
	longBreak?: number;
}

export interface Project {
	id: number;
	name: string;
	status: string;
	goal: string;
	progress: number;
	metric: string;
	metric_value: string;
	metric_target: string;
	githubRepo?: string;
	githubData?: GitHubData;
	deadline?: string;
	notes?: string;
	isFocus?: boolean;
	pomodoroSessions?: number;
	url?: string;
	lastFocusDate?: string;
	completedDate?: string;
	createdDate?: string;
}

export interface WidgetData {
	projects: Project[];
	habits: Habit[];
	quotes: string[];
	pomodoroDurations?: PomodoroDurations;
	pomodoroSessionsDate?: string;
	pomodoroSessions?: number;
	pomodoroAutoStart?: boolean;
	pomodoroSessionGoal?: number;
	collapsedSections?: string[];
	quoteInterval?: number;
	pomodoroLongBreakInterval?: number;
	pomodoroNotify?: boolean;
	pomodoroHistory?: PomodoroDay[];
	sectionOrder?: string[];
	todayIntention?: string;
	todayIntentionDate?: string;
	todayIntentionDone?: boolean;
	intentionHistory?: IntentionEntry[];
	weekGoal?: string;
	weekGoalDate?: string;
	weekGoalDone?: boolean;
	monthGoal?: string;
	monthGoalDate?: string;
	monthGoalDone?: boolean;
	quarterGoal?: string;
	quarterGoalDate?: string;
	quarterGoalDone?: boolean;
	yearGoal?: string;
	yearGoalDate?: string;
	yearGoalDone?: boolean;
	pomodoroLifetimeMins?: number;
	habitsAllDoneDate?: string;
	perfectDayBestStreak?: number;
	intentionDoneBestStreak?: number;
	focusBestStreak?: number;
	weekGoalHistory?: GoalEntry[];
	monthGoalHistory?: GoalEntry[];
	quarterGoalHistory?: GoalEntry[];
	yearGoalHistory?: GoalEntry[];
	momentumHistory?: MomentumEntry[];
	habitEveningRemindDate?: string;
	intentionMorningRemindDate?: string;
	intentionEveningRemindDate?: string;
	pomodoroMorningRemindDate?: string;
	pomodoroEveningRemindDate?: string;
	habitMilestoneApproachDate?: string;
	weeklyReviewRemindDate?: string;
	weeklyGoalMorningRemindDate?: string;
	monthlyGoalMorningRemindDate?: string;
	quarterlyGoalMorningRemindDate?: string;
	weeklyHabitReportDate?: string;
	monthGoalRemindDate?: string;
	quarterGoalRemindDate?: string;
	yearGoalRemindDate?: string;
	momentumEveningDigestDate?: string;
	weeklyMomentumReportDate?: string;
	weeklyPomodoroReportDate?: string;
	weeklyGoalReportDate?: string;
	monthlyGoalReportDate?: string;
	quarterlyGoalReportDate?: string;
	yearlyGoalReportDate?: string;
	habitsSound?: boolean;
	pomodoroSound?: boolean;
	hiddenSections?: string[];
	habitLifetimeTotalCheckins?: number;
	habitMorningRemindDate?: string;
	momentumMorningRemindDate?: string;
	yearlyGoalMorningRemindDate?: string;
	weeklyIntentionReportDate?: string;
	monthlyIntentionReportDate?: string;
	quarterlyIntentionReportDate?: string;
	yearlyIntentionReportDate?: string;
	monthlyHabitReportDate?: string;
	quarterlyHabitReportDate?: string;
	yearlyHabitReportDate?: string;
	weeklyPerfectDayReportDate?: string;
	monthlyPerfectDayReportDate?: string;
	quarterlyPerfectDayReportDate?: string;
	yearlyPerfectDayReportDate?: string;
	monthlyMomentumReportDate?: string;
	quarterlyMomentumReportDate?: string;
	yearlyMomentumReportDate?: string;
	monthlyPomodoroReportDate?: string;
	quarterlyPomodoroReportDate?: string;
	yearlyPomodoroReportDate?: string;
}

export interface WindowPosition {
	x: number;
	y: number;
}

export interface WindowSize {
	width: number;
	height: number;
}

export interface WidgetSettings {
	position: WindowPosition;
	size: WindowSize;
	opacity: number;
	theme: string;
	clockFormat: string;
	githubPat?: string;
	githubRefreshInterval?: number;
	pinned?: boolean;
}

